version: '3.8'

services:

    database:
      container_name: database_docker
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: car_brand
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql

    php:
      container_name: php_docker
      build:
        context: ./php
      ports:
        - '9000:9000'
      volumes:
        - ./recrutation_task:/var/www
      depends_on:
        - database

    nginx:
      container_name: nginx_docker
      image: nginx:stable-alpine
      ports:
        - '8080:80'
      volumes:
        - ./recrutation_task:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database
